/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.Client;
import Reproductores.InterfazReproductor;
import Reproductores.VideoPlayerConBiblioteca;

/**
 *
 * @author damia
 */
public class BetaInterfazDeUsuario extends javax.swing.JFrame {

    /**
     * Creates new form BetaInterfazDeUsuario
     */
    public BetaInterfazDeUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDescargaDeArchivos = new javax.swing.JButton();
        btnReproductorVideo = new javax.swing.JButton();
        btnReproductorDeMusica = new javax.swing.JButton();
        btnReproductorDeDocumentos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(60, 51, 125));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Bienvenido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 6, 119, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Reproductores");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 151, 165, -1));

        btnDescargaDeArchivos.setBackground(new java.awt.Color(154, 178, 213));
        btnDescargaDeArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDescargaDeArchivosMouseClicked(evt);
            }
        });
        jPanel1.add(btnDescargaDeArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 94, -1, 26));

        btnReproductorVideo.setBackground(new java.awt.Color(0, 0, 255));
        btnReproductorVideo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReproductorVideoMouseClicked(evt);
            }
        });
        jPanel1.add(btnReproductorVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 247, -1, 21));

        btnReproductorDeMusica.setBackground(new java.awt.Color(204, 0, 204));
        btnReproductorDeMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReproductorDeMusicaMouseClicked(evt);
            }
        });
        btnReproductorDeMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproductorDeMusicaActionPerformed(evt);
            }
        });
        jPanel1.add(btnReproductorDeMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 247, -1, 21));

        btnReproductorDeDocumentos.setBackground(new java.awt.Color(255, 0, 0));
        btnReproductorDeDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproductorDeDocumentosActionPerformed(evt);
            }
        });
        jPanel1.add(btnReproductorDeDocumentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 247, -1, 21));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Video");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 218, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Música");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 218, 51, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Documentos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 218, 83, -1));

        jLabel6.setText("Descargar contenido");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 59, 118, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReproductorDeDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproductorDeDocumentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReproductorDeDocumentosActionPerformed

    private void btnDescargaDeArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDescargaDeArchivosMouseClicked
      this.dispose();
    Client nuevaVentana = new Client();
    nuevaVentana.setVisible(true);


       
    }//GEN-LAST:event_btnDescargaDeArchivosMouseClicked

    private void btnReproductorVideoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReproductorVideoMouseClicked
    this.dispose();
    VideoPlayerConBiblioteca nuevaVentana = new VideoPlayerConBiblioteca();
    nuevaVentana.ejecutar();
    }//GEN-LAST:event_btnReproductorVideoMouseClicked

    private void btnReproductorDeMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproductorDeMusicaActionPerformed
        // TODO add your handling code here:  
        this.dispose();   
        InterfazReproductor player = new InterfazReproductor();
        player.setVisible(true);
    }//GEN-LAST:event_btnReproductorDeMusicaActionPerformed

    private void btnReproductorDeMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReproductorDeMusicaMouseClicked
      
    }//GEN-LAST:event_btnReproductorDeMusicaMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDescargaDeArchivos;
    private javax.swing.JButton btnReproductorDeDocumentos;
    private javax.swing.JButton btnReproductorDeMusica;
    private javax.swing.JButton btnReproductorVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
